# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_kelompok.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from kelompok import Kelompok
from mahasiswa import Mahasiswa
from instansi import Instansi
from dosen import Dosen
import dashboard_kelompok_admin as ka

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 230, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_cari = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cari.setGeometry(QtCore.QRect(510, 80, 191, 31))
        self.pushButton_cari.setObjectName("pushButton_cari")
        self.comboBox_instansi = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_instansi.setGeometry(QtCore.QRect(120, 350, 581, 31))
        self.comboBox_instansi.setObjectName("comboBox_instansi")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 330, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_tambah = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tambah.setGeometry(QtCore.QRect(330, 460, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tambah.setFont(font)
        self.btn_tambah.setObjectName("btn_tambah")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 280, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(670, 470, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 380, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_anggota1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_anggota1.setGeometry(QtCore.QRect(120, 250, 581, 31))
        self.comboBox_anggota1.setObjectName("comboBox_anggota1")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(120, 140, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setText("")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(119, 63, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_ketua = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ketua.setGeometry(QtCore.QRect(120, 200, 581, 31))
        self.comboBox_ketua.setObjectName("comboBox_ketua")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 120, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(120, 400, 581, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_anggota2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_anggota2.setGeometry(QtCore.QRect(120, 300, 581, 31))
        self.comboBox_anggota2.setObjectName("comboBox_anggota2")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(120, 80, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MainWindow = MainWindow
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.getDatamhs()
        self.getDatains()
        self.getDatadsn()
        self.pushButton_cari.clicked.connect(self.CariData)
        self.btn_tambah.clicked.connect(self.DeleteData)
        self.btn_kembali.clicked.connect(self.Kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Anggota 1 :"))
        self.pushButton_cari.setText(_translate("MainWindow", "CARI!!!!"))
        self.label_9.setText(_translate("MainWindow", "Instansi :"))
        self.btn_tambah.setText(_translate("MainWindow", "DELETE!!!"))
        self.label_6.setText(_translate("MainWindow", "Anggota 2 :"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))
        self.label_7.setText(_translate("MainWindow", "DELETE KELOMPOK"))
        self.label_10.setText(_translate("MainWindow", "DOSEN :"))
        self.label_8.setText(_translate("MainWindow", "ID_KELOMPOK :"))
        self.label_3.setText(_translate("MainWindow", "NAMA :"))
        self.label_4.setText(_translate("MainWindow", "KETUA :"))

    def getDatamhs(self,):
        data=Mahasiswa.select_mhs()
        print(data)
        self.comboBox_ketua.addItems(data)
        self.comboBox_anggota1.addItems(data)
        self.comboBox_anggota2.addItems(data)

    def getDatains(self):
        data=Instansi.select_ins()
        print(data)
        self.comboBox_instansi.addItems(data)

    def getDatadsn(self):
        data=Dosen.select_dsn()
        print(data)
        self.comboBox_5.addItems(data)

    def CariData(self):
        id=self.lineEdit_id.text()
        data=Kelompok.select_data_by_id([id])
        nama=data[1]
        ketua=data[2]
        anggota_1=data[3]
        anggota_2=data[4]
        instansi=data[5]
        dosen=data[6]
        self.lineEdit_nama.setText(str(nama))
        self.comboBox_ketua.setCurrentText(str(ketua))
        self.comboBox_anggota1.setCurrentText(str(anggota_1))
        self.comboBox_anggota2.setCurrentText(str(anggota_2))
        self.comboBox_instansi.setCurrentText(str(instansi))
        self.comboBox_5.setCurrentText(str(dosen))

    def DeleteData(self):
        id = self.lineEdit_id.text()
        Kelompok.delete_kelompok(id)
        self.lineEdit_id.clear()
        self.lineEdit_nama.clear()
        self.comboBox_ketua.setCurrentIndex(0)
        self.comboBox_anggota1.setCurrentIndex(0)
        self.comboBox_anggota2.setCurrentIndex(0)
        self.comboBox_instansi.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)

    def Kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ka.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
