# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_mhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mdlmahasiswa import Mahasiswa
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 85, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(87, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(87, 200, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(87, 260, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(87, 320, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(87, 380, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_nim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nim.setGeometry(QtCore.QRect(87, 160, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nim.setFont(font)
        self.lineEdit_nim.setObjectName("lineEdit_nim")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(87, 220, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.lineEdit_kelas = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kelas.setGeometry(QtCore.QRect(87, 280, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_kelas.setFont(font)
        self.lineEdit_kelas.setObjectName("lineEdit_kelas")
        self.lineEdit_alamat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alamat.setGeometry(QtCore.QRect(87, 340, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_alamat.setFont(font)
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.lineEdit_no_hp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_no_hp.setGeometry(QtCore.QRect(87, 400, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_no_hp.setFont(font)
        self.lineEdit_no_hp.setObjectName("lineEdit_no_hp")
        self.btn_tambah = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tambah.setGeometry(QtCore.QRect(270, 490, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tambah.setFont(font)
        self.btn_tambah.setObjectName("btn_tambah")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 85, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(87, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(610, 590, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.MainWindow = MainWindow

        self.btn_tambah.clicked.connect(self.TambahMahasiswa)
        #self.btn_kembali.clicked.connect(self.kembali)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TAMBAH DATA MAHASIWA"))
        self.label_2.setText(_translate("MainWindow", "NIM :"))
        self.label_3.setText(_translate("MainWindow", "NAMA MAHASISWA :"))
        self.label_4.setText(_translate("MainWindow", "KELAS MAHASISWA :"))
        self.label_5.setText(_translate("MainWindow", "ALAMAT MAHASISWA :"))
        self.label_6.setText(_translate("MainWindow", "NO HP MAHSISWA :"))
        self.btn_tambah.setText(_translate("MainWindow", "TAMBAHKAN!!!"))
        self.label_7.setText(_translate("MainWindow", "TAMBAH DATA MAHASIWA"))
        self.label_8.setText(_translate("MainWindow", "NIM :"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))

    def TambahMahasiswa(self):
        nim_baru = self.lineEdit_nim.text()
        nama_baru = self.lineEdit_nama.text()
        kelas_baru = self.lineEdit_kelas.text()
        alamat_baru = self.lineEdit_alamat.text()
        nohp_baru = self.lineEdit_no_hp.text()

        # Validasi data
        if not nim_baru or not nama_baru or not alamat_baru or not kelas_baru or not nohp_baru:
            QMessageBox.warning(self.MainWindow, 'Peringatan', 'Silakan isi semua data!')
            return

        # Validasi untuk NIM berupa angka
        if not nim_baru.isdigit():
            QMessageBox.warning(self.MainWindow, 'Peringatan', 'NIM harus berupa angka!')
            return


        # Memanggil fungsi insert_data dan menyimpan hasilnya
        result = Mahasiswa.insert_data(nim_baru, nama_baru, kelas_baru, alamat_baru, nohp_baru)

        # Memeriksa hasil operasi penyimpanan data
        if result:
            # Jika berhasil, tampilkan QMessageBox informasi
            QMessageBox.information(self.MainWindow, 'Informasi', 'Data berhasil disimpan!')
        else:
            # Jika gagal, tampilkan QMessageBox peringatan
            QMessageBox.information(self.MainWindow, 'Informasi', 'Data berhasil disimpan!')

        self.lineEdit_nim.clear()
        self.lineEdit_nama.clear()
        self.lineEdit_kelas.clear()
        self.lineEdit_alamat.clear()
        self.lineEdit_no_hp.clear()


    # def kembali(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = ma.Ui_MainWindow()
    #     self.ui.setupUi(self.window)
    #     self.window.show()
    #     self.cl.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
