# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_mhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mdlmahasiswa import Mahasiswa
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_nim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nim.setGeometry(QtCore.QRect(140, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nim.setFont(font)
        self.lineEdit_nim.setText("")
        self.lineEdit_nim.setObjectName("lineEdit_nim")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 310, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 250, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_hapus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hapus.setGeometry(QtCore.QRect(320, 490, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_hapus.setFont(font)
        self.btn_hapus.setObjectName("btn_hapus")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cari = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cari.setGeometry(QtCore.QRect(330, 120, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cari.setFont(font)
        self.btn_cari.setObjectName("btn_cari")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 370, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 190, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_nama = QtWidgets.QLabel(self.centralwidget)
        self.label_nama.setGeometry(QtCore.QRect(130, 220, 441, 18))
        self.label_nama.setText("")
        self.label_nama.setObjectName("label_nama")
        self.label_kelas = QtWidgets.QLabel(self.centralwidget)
        self.label_kelas.setGeometry(QtCore.QRect(130, 280, 441, 23))
        self.label_kelas.setText("")
        self.label_kelas.setObjectName("label_kelas")
        self.label_alamat = QtWidgets.QLabel(self.centralwidget)
        self.label_alamat.setGeometry(QtCore.QRect(130, 340, 441, 22))
        self.label_alamat.setText("")
        self.label_alamat.setObjectName("label_alamat")
        self.label_nohp = QtWidgets.QLabel(self.centralwidget)
        self.label_nohp.setGeometry(QtCore.QRect(130, 393, 441, 23))
        self.label_nohp.setText("")
        self.label_nohp.setObjectName("label_nohp")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(610, 450, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        self.label_dosen = QtWidgets.QLabel(self.centralwidget)
        self.label_dosen.setGeometry(QtCore.QRect(125, 448, 441, 26))
        self.label_dosen.setText("")
        self.label_dosen.setObjectName("label_dosen")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.MainWindow = MainWindow

        self.btn_cari.clicked.connect(self.CariData)
        self.btn_hapus.clicked.connect(self.DeleteData)
        # self.btn_kembali.clicked.connect(self.DashboardAdmin)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "ALAMAT MAHASISWA :"))
        self.label_2.setText(_translate("MainWindow", "NIM :"))
        self.label_4.setText(_translate("MainWindow", "KELAS MAHASISWA :"))
        self.btn_hapus.setText(_translate("MainWindow", "HAPUS!!"))
        self.label.setText(_translate("MainWindow", "HAPUS DATA MAHASIWA"))
        self.btn_cari.setText(_translate("MainWindow", "CARIKAN!"))
        self.label_6.setText(_translate("MainWindow", "NO HP MAHASISWA :"))
        self.label_3.setText(_translate("MainWindow", "NAMA MAHASISWA :"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))

    def CariData(self):
        nim=self.lineEdit_nim.text()
        data=Mahasiswa.select_data_by_nim([nim])
        nama=data[1]
        kelas=data[2]
        alamat=data[3]
        hp=data[4]
        self.label_nama.setText(str(nama))
        self.label_kelas.setText(str(kelas))
        self.label_alamat.setText(str(alamat))
        self.label_nohp.setText(str(hp))

    

    def DeleteData(self):
        nim=self.lineEdit_nim.text()
        Mahasiswa.delete_data(nim)
        self.label_nama.clear()
        self.label_kelas.clear()
        self.label_alamat.clear()
        self.label_nohp.clear()
        QMessageBox.information(self.MainWindow, 'Informasi', 'Data berhasil Dihapus!')
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
