# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_admin_ubah_data_dosen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dosen import Dosen
import dosen_admin as da

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.Main = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 610)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ubah_data_mhs = QtWidgets.QLabel(self.centralwidget)
        self.label_ubah_data_mhs.setGeometry(QtCore.QRect(170, 30, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_ubah_data_mhs.setFont(font)
        self.label_ubah_data_mhs.setObjectName("label_ubah_data_mhs")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_hp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_hp.setGeometry(QtCore.QRect(50, 320, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_hp.setFont(font)
        self.lineEdit_hp.setObjectName("lineEdit_hp")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_alamat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alamat.setGeometry(QtCore.QRect(50, 260, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_alamat.setFont(font)
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(50, 200, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setText("")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_nip = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nip.setGeometry(QtCore.QRect(110, 110, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nip.setFont(font)
        self.lineEdit_nip.setText("")
        self.lineEdit_nip.setObjectName("lineEdit_nip")
        self.btn_ubah = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ubah.setGeometry(QtCore.QRect(310, 500, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ubah.setFont(font)
        self.btn_ubah.setObjectName("btn_ubah")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 240, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_cari = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cari.setGeometry(QtCore.QRect(410, 110, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cari.setFont(font)
        self.btn_cari.setObjectName("btn_cari")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(620, 510, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_cari.clicked.connect(self.CariData)
        self.btn_ubah.clicked.connect(self.UpdateData)
        self.btn_kembali.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ubah_data_mhs.setText(_translate("MainWindow", "UBAH DATA DOSEN"))
        self.label_3.setText(_translate("MainWindow", "NAMA DOSEN :"))
        self.label_5.setText(_translate("MainWindow", "NOHP DOSEN:"))
        self.label_2.setText(_translate("MainWindow", "NIP :"))
        self.btn_ubah.setText(_translate("MainWindow", "MENGUBAH!!!"))
        self.label_4.setText(_translate("MainWindow", "ALAMAT DOSEN :"))
        self.btn_cari.setText(_translate("MainWindow", "CARIKAN!"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI")) 

    def CariData(self):
        nip=self.lineEdit_nip.text()
        data=Dosen.select_data_by_nip([nip])
        nama=data[1]
        alamat=data[2]
        hp=data[3]
        self.lineEdit_nama.setText(str(nama))
        self.lineEdit_alamat.setText(str(alamat))
        self.lineEdit_hp.setText(str(hp))
        

    def UpdateData(self):
        nip_baru=self.lineEdit_nip.text()
        nama_baru=self.lineEdit_nama.text()
        alamat_baru=self.lineEdit_alamat.text()
        hp_baru=self.lineEdit_hp.text()
        Dosen.update_data_dosen(nama_baru,alamat_baru,hp_baru,nip_baru)
        self.lineEdit_nip.clear()
        self.lineEdit_nama.clear()
        self.lineEdit_alamat.clear()
        self.lineEdit_hp.clear()
        

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show() 
        self.Main.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
