# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_mhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mdlmahasiswa import Mahasiswa

from PyQt5.QtWidgets import QMessageBox
# from mdlDosenBox import Instansi
# from mdlDosenBox import Dosen

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 704)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ubah_data_mhs = QtWidgets.QLabel(self.centralwidget)
        self.label_ubah_data_mhs.setGeometry(QtCore.QRect(250, 60, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_ubah_data_mhs.setFont(font)
        self.label_ubah_data_mhs.setObjectName("label_ubah_data_mhs")
        self.lineEdit_no_hp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_no_hp.setGeometry(QtCore.QRect(130, 410, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_no_hp.setFont(font)
        self.lineEdit_no_hp.setObjectName("lineEdit_no_hp")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 210, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_alamat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alamat.setGeometry(QtCore.QRect(130, 350, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_alamat.setFont(font)
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 330, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_kelas_mhs = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kelas_mhs.setGeometry(QtCore.QRect(130, 290, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_kelas_mhs.setFont(font)
        self.lineEdit_kelas_mhs.setObjectName("lineEdit_kelas_mhs")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(130, 230, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setText("")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_nim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nim.setGeometry(QtCore.QRect(190, 140, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nim.setFont(font)
        self.lineEdit_nim.setText("")
        self.lineEdit_nim.setObjectName("lineEdit_nim")
        self.btn_ubah = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ubah.setGeometry(QtCore.QRect(360, 490, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ubah.setFont(font)
        self.btn_ubah.setObjectName("btn_ubah")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 270, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 390, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_cari = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cari.setGeometry(QtCore.QRect(490, 140, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cari.setFont(font)
        self.btn_cari.setObjectName("btn_cari")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(600, 580, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.MainWindow = MainWindow
        
        self.btn_cari.clicked.connect(self.CariData)
        self.btn_ubah.clicked.connect(self.UpdateData)
        # self.btn_kembali.clicked.connect(self.kembali)

        # self.getDataDosen()
        # self.getDataInatansi()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ubah_data_mhs.setText(_translate("MainWindow", "UBAH DATA MAHASIWA"))
        self.label_3.setText(_translate("MainWindow", "NAMA MAHASISWA :"))
        self.label_5.setText(_translate("MainWindow", "ALAMAT MAHASISWA :"))
        self.label_2.setText(_translate("MainWindow", "NIM :"))
        self.btn_ubah.setText(_translate("MainWindow", "MENGUBAH!!!"))
        self.label_4.setText(_translate("MainWindow", "KELAS MAHASISWA :"))
        self.label_6.setText(_translate("MainWindow", "NO HP MAHASISWA :"))
        self.btn_cari.setText(_translate("MainWindow", "CARIKAN!"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))


    def CariData(self):
        nim=self.lineEdit_nim.text()
        data=Mahasiswa.select_data_by_nim([nim])
        nama=data[1]
        kelas=data[2]
        alamat=data[3]
        hp=data[4]
        self.lineEdit_nama.setText(str(nama))
        self.lineEdit_kelas_mhs.setText(str(kelas))
        self.lineEdit_alamat.setText(str(alamat))
        self.lineEdit_no_hp.setText(str(hp))
        

    def UpdateData(self):
        nim_baru=self.lineEdit_nim.text()
        nama_baru=self.lineEdit_nama.text()
        kelas_baru=self.lineEdit_kelas_mhs.text()
        alamat_baru=self.lineEdit_alamat.text()
        hp_baru=self.lineEdit_no_hp.text()
        Mahasiswa.update_data_mahasiswa(nama_baru,kelas_baru,alamat_baru,hp_baru,nim_baru)
        QMessageBox.information(self.MainWindow, 'Informasi', 'Data berhasil Diperbarui!')
        self.lineEdit_nim.clear()
        self.lineEdit_nama.clear()
        self.lineEdit_kelas_mhs.clear()
        self.lineEdit_alamat.clear()
        self.lineEdit_no_hp.clear()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
