# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_tambah_data_mhs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tambah_data_mhs.setGeometry(QtCore.QRect(130, 120, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_tambah_data_mhs.setFont(font)
        self.btn_tambah_data_mhs.setObjectName("btn_tambah_data_mhs")
        self.btn_ubah_data_mhs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ubah_data_mhs.setGeometry(QtCore.QRect(130, 210, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_ubah_data_mhs.setFont(font)
        self.btn_ubah_data_mhs.setObjectName("btn_ubah_data_mhs")
        self.btn_delete_data_mhs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_data_mhs.setGeometry(QtCore.QRect(130, 300, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_delete_data_mhs.setFont(font)
        self.btn_delete_data_mhs.setObjectName("btn_delete_data_mhs")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(330, 412, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DASHBOARD ADMIN"))
        self.btn_tambah_data_mhs.setText(_translate("MainWindow", "MAHASISWA"))
        self.btn_ubah_data_mhs.setText(_translate("MainWindow", "DOSEN"))
        self.btn_delete_data_mhs.setText(_translate("MainWindow", "INSTANSI"))
        self.btn.setText(_translate("MainWindow", "LOGOUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
