# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_admin_tambah_data_instansi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from instansi import Instansi
#import instansi_admin as ia



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.cl = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 240, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_nim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nim.setGeometry(QtCore.QRect(70, 140, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nim.setFont(font)
        self.lineEdit_nim.setObjectName("lineEdit_nim")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(70, 200, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.lineEdit_kelas = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kelas.setGeometry(QtCore.QRect(70, 260, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_kelas.setFont(font)
        self.lineEdit_kelas.setObjectName("lineEdit_kelas")
        self.btn_tambah = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tambah.setGeometry(QtCore.QRect(270, 430, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tambah.setFont(font)
        self.btn_tambah.setObjectName("btn_tambah")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(163, 35, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(71, 122, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(660, 480, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_tambah.clicked.connect(self.TambahInstansi)
        #self.btn_kembali.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "NAMA INSTANSI :"))
        self.label_4.setText(_translate("MainWindow", "ALAMAT INSTANSI :"))
        self.btn_tambah.setText(_translate("MainWindow", "TAMBAHKAN!!!"))
        self.label_7.setText(_translate("MainWindow", "TAMBAH DATA INSTANSI"))
        self.label_8.setText(_translate("MainWindow", "ID :"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))

    def TambahInstansi(self):
        id_baru=self.lineEdit_nim.text()
        nama_baru=self.lineEdit_nama.text()
        alamat_baru=self.lineEdit_kelas.text()
        Instansi.insert_ins(id_baru,nama_baru,alamat_baru)
        self.lineEdit_nim.clear()
        self.lineEdit_nama.clear()
        self.lineEdit_kelas.clear()
        

    # def kembali(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = ua.Ui_MainWindow()
    #     self.ui.setupUi(self.window)
    #     self.window.show()
    #     self.cl.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
