# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_mahasiswa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import login as l


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.cl = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_dashboard_mhs = QtWidgets.QLabel(self.centralwidget)
        self.label_dashboard_mhs.setGeometry(QtCore.QRect(180, 50, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_dashboard_mhs.setFont(font)
        self.label_dashboard_mhs.setObjectName("label_dashboard_mhs")
        self.btn_lihat_data_mhs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lihat_data_mhs.setGeometry(QtCore.QRect(120, 180, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_lihat_data_mhs.setFont(font)
        self.btn_lihat_data_mhs.setObjectName("btn_lihat_data_mhs")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(330, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setObjectName("btn_logout")
        self.btn_lihat_data_instansi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lihat_data_instansi.setGeometry(QtCore.QRect(120, 260, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_lihat_data_instansi.setFont(font)
        self.btn_lihat_data_instansi.setObjectName("btn_lihat_data_instansi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btn_logout.clicked.connect(self.logout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_dashboard_mhs.setText(_translate("MainWindow", "DASHBOARD MAHASISWA"))
        self.btn_lihat_data_mhs.setText(_translate("MainWindow", "LIHAT DATA MAHASISWA"))
        self.btn_logout.setText(_translate("MainWindow", "LOGOUT"))
        self.btn_lihat_data_instansi.setText(_translate("MainWindow", "LIHAT DATA INSTANSI"))

    def logout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = l.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.cl.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
