# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_admin_delete_data_dosen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dosen import Dosen
import dashboard_dosen_admin as dda

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.cl=MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_nim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nim.setGeometry(QtCore.QRect(160, 110, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nim.setFont(font)
        self.lineEdit_nim.setText("")
        self.lineEdit_nim.setObjectName("lineEdit_nim")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(126, 251, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_hapus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hapus.setGeometry(QtCore.QRect(280, 430, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_hapus.setFont(font)
        self.btn_hapus.setObjectName("btn_hapus")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cari = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cari.setGeometry(QtCore.QRect(320, 120, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cari.setFont(font)
        self.btn_cari.setObjectName("btn_cari")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(127, 313, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 190, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_nama = QtWidgets.QLabel(self.centralwidget)
        self.label_nama.setGeometry(QtCore.QRect(130, 220, 441, 16))
        self.label_nama.setText("")
        self.label_nama.setObjectName("label_nama")
        self.label_alamat = QtWidgets.QLabel(self.centralwidget)
        self.label_alamat.setGeometry(QtCore.QRect(128, 278, 441, 24))
        self.label_alamat.setText("")
        self.label_alamat.setObjectName("label_alamat")
        self.label_nohp = QtWidgets.QLabel(self.centralwidget)
        self.label_nohp.setGeometry(QtCore.QRect(127, 340, 441, 26))
        self.label_nohp.setText("")
        self.label_nohp.setObjectName("label_nohp")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(610, 450, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_cari.clicked.connect(self.CariData)
        self.btn_kembali.clicked.connect(self.kembali)
        self.btn_hapus.clicked.connect(self.Deletedata)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "ALAMAT DOSEN :"))
        self.label_2.setText(_translate("MainWindow", "NIP :"))
        self.btn_hapus.setText(_translate("MainWindow", "HAPUS!!"))
        self.label.setText(_translate("MainWindow", "HAPUS DATA DOSEN"))
        self.btn_cari.setText(_translate("MainWindow", "CARIKAN!"))
        self.label_6.setText(_translate("MainWindow", "NO HP DOSEN :"))
        self.label_3.setText(_translate("MainWindow", "NAMA DOSEN :"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))
        
    # def CariData(self):
    #     nip=self.lineEdit_nim.text()
    #     data=Dosen.select_data_by_nip([nip])
    #     nama=data[1]
    #     alamat=data[2]
    #     nohp=data[3]
    #     self.label_nama.setText(str(nama))
    #     self.label_alamat.setText(str(alamat))
    #     self.label_nohp.setText(str(nohp))
        
    def CariData(self):
        nip=self.lineEdit_nim.text()
        data=Dosen.select_data_by_nip([nip]) #panggil method diclass barang
        nama=data[1]
        alamat=data[2]
        nohp=data[3]
        self.label_nama.setText(str(nama))
        self.label_alamat.setText(str(alamat))
        self.label_nohp.setText(str(nohp))
        
        
    def Deletedata(self):
        nip = self.lineEdit_nim.text()
        Dosen.delete_ins(nip)
        self.label_nama.clear()
        self.label_alamat.clear()
        self.label_nohp.clear()
        
    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dda.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.cl.close()  
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
