# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# import sys
# sys.path.append("E:\\Python\Kuliah PBO\\Python_Database\\GUI_python\\adminku\\input_user.py")


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from update_user import Ui_update
from input_user import Ui_insert
from delete_user import Ui_delete
from lihat_user import Ui_DataUser

class Ui_DashboardAdmin(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 300)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(160, 20, 300, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.insert_data = QtWidgets.QPushButton(Dialog)
        self.insert_data.setGeometry(QtCore.QRect(60, 70, 150, 61))
        self.insert_data.setObjectName("insert_data_kasir")
        self.lihat_data = QtWidgets.QPushButton(Dialog)
        self.lihat_data.setGeometry(QtCore.QRect(280, 170, 150, 61))
        self.lihat_data.setObjectName("lihat_data_kasir")
        self.delete_data = QtWidgets.QPushButton(Dialog)
        self.delete_data.setGeometry(QtCore.QRect(60, 170, 150, 61))
        self.delete_data.setObjectName("delete_data_kasir")
        self.update_data = QtWidgets.QPushButton(Dialog)
        self.update_data.setGeometry(QtCore.QRect(280, 70, 150, 61))
        self.update_data.setObjectName("update_data")
        self.btn_logout = QtWidgets.QPushButton(Dialog)
        self.btn_logout.setGeometry(QtCore.QRect(210, 260, 75, 23))
        self.btn_logout.setObjectName("btn_logout")

        self.insert_data.clicked.connect(self.open_insert_form)
        self.update_data.clicked.connect(self.open_edit_form)
        self.delete_data.clicked.connect(self.open_delete_form)
        self.lihat_data.clicked.connect(self.open_view_form)
        self.btn_logout.clicked.connect(self.logout)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def open_insert_form(self):
        # Membuka form insert
        self.Dialog.close()
        self.insert_form = QDialog()
        self.ui_insert_form = Ui_insert()
        self.ui_insert_form.setupUi(self.insert_form)
        self.insert_form.show()

    def open_edit_form(self):
        # Membuka form edit
        self.Dialog.close()
        self.edit_form = QDialog()
        self.ui_edit_form = Ui_update()
        self.ui_edit_form.setupUi(self.edit_form)
        self.edit_form.show()

    def open_delete_form(self):
        # Membuka form delete
        self.Dialog.close()
        self.delete_form = QDialog()
        self.ui_delete_form = Ui_delete()
        self.ui_delete_form.setupUi(self.delete_form)
        self.delete_form.show()

    def open_view_form(self):
        # Membuka form view
        self.Dialog.close()
        self.view_form = QDialog()
        self.ui_view_form = Ui_DataUser()
        self.ui_view_form.setupUi(self.view_form)
        self.view_form.show()
        
    def logout(self):
        self.Dialog.close()
        
        # Open the login form
        from login import Ui_Dialog
        self.login_form = QtWidgets.QDialog()
        self.ui_login_form = Ui_Dialog()
        self.ui_login_form.setupUi(self.login_form)
        self.login_form.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dashboard Admin"))
        self.label_6.setText(_translate("Dialog", "DASHBOARD ADMIN"))
        self.insert_data.setText(_translate("Dialog", "INSERT DATA USER"))
        self.delete_data.setText(_translate("Dialog", "DELETE DATA USER"))
        self.lihat_data.setText(_translate("Dialog", "LIHAT DATA USER"))
        self.update_data.setText(_translate("Dialog", "UPDATE DATA USER"))
        self.btn_logout.setText(_translate("Dashboard Kasir","Log Out"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DashboardAdmin()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
