# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_pegawai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from insert_pegawai import Ui_Insert_Pegawai
from update_pegawai import Ui_Update_Pegawai
from delete_pegawai import Ui_Delete_Pegawai 
from lihat_pegawai import Ui_Form


class Ui_Dashboardpegawai(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dashboard Pegawai")
        Dialog.resize(500, 300)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 2, 521, 311))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/back.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(120, 20, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/Dashboard Pegawai.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()

        
        
        self.insert_data_pegawai = QtWidgets.QPushButton(Dialog)
        self.insert_data_pegawai.setGeometry(QtCore.QRect(70, 70, 150, 61))
        self.insert_data_pegawai.setObjectName("insert_data_pegawai")
        self.insert_data_pegawai.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.insert_data_pegawai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/insert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insert_data_pegawai.setIcon(icon)
        self.insert_data_pegawai.setIconSize(QtCore.QSize(140, 140))
        
        self.lihat_data_pegawai = QtWidgets.QPushButton(Dialog)
        self.lihat_data_pegawai.setGeometry(QtCore.QRect(280, 170, 150, 61))
        self.lihat_data_pegawai.setObjectName("lihat_data_pegawai")
        self.lihat_data_pegawai.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lihat_data_pegawai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lihat_data_pegawai.setIcon(icon)
        self.lihat_data_pegawai.setIconSize(QtCore.QSize(140, 140))
        
        self.delete_data_pegawai = QtWidgets.QPushButton(Dialog)
        self.delete_data_pegawai.setGeometry(QtCore.QRect(70, 170, 150, 61))
        self.delete_data_pegawai.setObjectName("delete_data_pegawai")
        self.delete_data_pegawai.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.delete_data_pegawai.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_data_pegawai.setIcon(icon)
        self.delete_data_pegawai.setIconSize(QtCore.QSize(140, 140))
        
        self.update_data = QtWidgets.QPushButton(Dialog)
        self.update_data.setGeometry(QtCore.QRect(280, 70, 150, 61))
        self.update_data.setObjectName("update_data")
        self.update_data.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.update_data.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_data.setIcon(icon)
        self.update_data.setIconSize(QtCore.QSize(140, 140))
        
        self.btn_logout = QtWidgets.QPushButton(Dialog)
        self.btn_logout.setGeometry(QtCore.QRect(165, 250, 180, 41))
        self.btn_logout.setObjectName("btn_logout")
        self.btn_logout.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout.setIcon(icon)
        self.btn_logout.setIconSize(QtCore.QSize(140, 140))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-20, 180, 141, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/18915856-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_6.raise_()

        self.insert_data_pegawai.clicked.connect(self.insert_data)
        self.update_data.clicked.connect(self.open_edit_form)
        self.delete_data_pegawai.clicked.connect(self.open_delete_form)
        self.lihat_data_pegawai.clicked.connect(self.open_view_form)
        self.btn_logout.clicked.connect(self.logout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
            
    def insert_data(self):
        
        self.Dialog.close()
        # Membuka form insert
        self.insert_form = QDialog()
        self.ui_insert_form = Ui_Insert_Pegawai()
        self.ui_insert_form.setupUi(self.insert_form)
        self.insert_form.show()

    def open_edit_form(self):
        
        self.Dialog.close()
        # Membuka form edit
        self.edit_form = QDialog()
        self.ui_edit_form = Ui_Update_Pegawai()
        self.ui_edit_form.setupUi(self.edit_form)
        self.edit_form.show()

    def open_delete_form(self):
        # Membuka form delete
        self.Dialog.close()
        # from delete_brg import Ui_delete
        self.delete_form = QDialog()
        self.ui_delete_form = Ui_Delete_Pegawai()
        self.ui_delete_form.setupUi(self.delete_form)
        self.delete_form.show()
        
    def open_view_form(self):
        # Membuka form view
        self.Dialog.close()
        # from lihat_brg import Ui_Databrg 
        self.view_form = QDialog()
        self.ui_view_form = Ui_Form()
        self.ui_view_form.setupUi(self.view_form)
        self.view_form.show()
        
    def logout(self):
        self.Dialog.close()
        # Open the login form
        from login import Ui_Dialog
        self.login_form = QtWidgets.QDialog()
        self.ui_login_form = Ui_Dialog()
        self.ui_login_form.setupUi(self.login_form)
        self.login_form.show()
        


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dashboard pegawai", "Dashboard Pegawai"))
        self.label_6.setText(_translate("Dashboard pegawai", ""))
        self.insert_data_pegawai.setText(_translate("Dashboard pegawai", ""))
        self.lihat_data_pegawai.setText(_translate("Dashboard pegawai", ""))
        self.delete_data_pegawai.setText(_translate("Dashboard pegawai", ""))
        self.update_data.setText(_translate("Dashboard pegawai", ""))
        self.btn_logout.setText(_translate("Dashboard pegawai",""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dashboardpegawai()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
