# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_data_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Barang import Barang
from PyQt5.QtWidgets import QDialog

class Ui_delete(object):
    def setupUi(self, Dialog):
        self.Form = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(566, 368)
        self.btn_update = QtWidgets.QPushButton(Dialog)
        self.btn_update.setGeometry(QtCore.QRect(250, 280, 75, 23))
        self.btn_update.setObjectName("btn_update")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(150, 30, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.btn_kembali = QtWidgets.QPushButton(Dialog)
        self.btn_kembali.setGeometry(QtCore.QRect(170, 280, 75, 23))
        self.btn_kembali.setObjectName("btn_kembali")
        self.btn_kembali.setText("Kembali")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_id = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id.setGeometry(QtCore.QRect(200, 80, 113, 20))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 160, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox_2.setGeometry(QtCore.QRect(30, 370, 341, 32))
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 80, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 240, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(150, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 200, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_nama = QtWidgets.QLabel(Dialog)
        self.label_nama.setGeometry(QtCore.QRect(210, 110, 71, 31))
        self.label_nama.setText("")
        self.label_nama.setObjectName("label_nama")
        self.label_stok = QtWidgets.QLabel(Dialog)
        self.label_stok.setGeometry(QtCore.QRect(210, 150, 71, 31))
        self.label_stok.setText("")
        self.label_stok.setObjectName("label_stok")
        self.label_harga = QtWidgets.QLabel(Dialog)
        self.label_harga.setGeometry(QtCore.QRect(210, 190, 71, 31))
        self.label_harga.setText("")
        self.label_harga.setObjectName("label_harga")
        self.label_kategori = QtWidgets.QLabel(Dialog)
        self.label_kategori.setGeometry(QtCore.QRect(220, 230, 71, 31))
        self.label_kategori.setText("")
        self.label_kategori.setObjectName("label_kategori")
        
        self.pushButton.clicked.connect(self.cariData)
        self.btn_update.clicked.connect(self.Deletedata)
        self.btn_kembali.clicked.connect(self.kembali)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def cariData(self):
        id = self.lineEdit_id.text()
        data = Barang.select_data_by_id(id)
        nama = data[1]
        stok = data[2]
        harga = data[3]
        kategori = data[4]
        print(data)
        self.label_nama.setText(str(nama))
        self.label_stok.setText(str(stok))
        self.label_harga.setText(str(harga))
        self.label_kategori.setText(str(kategori))
        
    def Deletedata(self):
        id = self.lineEdit_id.text()
        Barang.delete_data(id)
        
        self.lineEdit_id.clear()
        self.label_nama.clear()
        self.label_stok.clear()
        self.label_harga.clear()
        self.label_kategori.clear()
        
    def kembali(self):
        self.Form.close()
        
        from dashboard_kasir import Ui_DashboardKasir
        self.dashboard_kasir = QDialog()
        self.ui_dashboard_kasir = Ui_DashboardKasir()
        self.ui_dashboard_kasir.setupUi(self.dashboard_kasir)
        self.dashboard_kasir.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_update.setText(_translate("Dialog", "DELETE"))
        self.label_6.setText(_translate("Dialog", "Delete Data Barang"))
        self.label.setText(_translate("Dialog", "Stok"))
        self.label_2.setText(_translate("Dialog", "ID"))
        self.pushButton.setText(_translate("Dialog", "Cari"))
        self.label_5.setText(_translate("Dialog", "Kategori"))
        self.label_3.setText(_translate("Dialog", "Nama"))
        self.label_4.setText(_translate("Dialog", "Harga"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_delete()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
