# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from User import User
from PyQt5.QtWidgets import QDialog

class Ui_insert(object):
    def setupUi(self, Insert_User):
        self.Form = Insert_User
        Insert_User.setObjectName("Insert User")
        Insert_User.resize(400, 300)
        self.label_judul = QtWidgets.QLabel(Insert_User)
        self.label_judul.setGeometry(QtCore.QRect(130, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setObjectName("label_judul")
        self.label_nama = QtWidgets.QLabel(Insert_User)
        self.label_nama.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label_nama.setObjectName("label_nama")
        self.label_username = QtWidgets.QLabel(Insert_User)
        self.label_username.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.label_username.setObjectName("label_username")
        self.label_pw = QtWidgets.QLabel(Insert_User)
        self.label_pw.setGeometry(QtCore.QRect(30, 150, 47, 13))
        self.label_pw.setObjectName("label_pw")
        self.label_lv = QtWidgets.QLabel(Insert_User)
        self.label_lv.setGeometry(QtCore.QRect(30, 200, 47, 13))
        self.label_lv.setObjectName("label_lv")
        self.L_nama = QtWidgets.QLineEdit(Insert_User)
        self.L_nama.setGeometry(QtCore.QRect(140, 60, 113, 20))
        self.L_nama.setObjectName("L_nama")
        self.L_username = QtWidgets.QLineEdit(Insert_User)
        self.L_username.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.L_username.setObjectName("L_username")
        self.L_pw = QtWidgets.QLineEdit(Insert_User)
        self.L_pw.setGeometry(QtCore.QRect(140, 150, 113, 20))
        self.L_pw.setObjectName("L_pw")
        self.comboBox_level = QtWidgets.QComboBox(Insert_User)
        self.comboBox_level.setGeometry(QtCore.QRect(140, 200, 113, 20))
        self.comboBox_level.setObjectName("comboBox_level")
        self.comboBox_level.addItem("Admin")
        self.comboBox_level.addItem("Kasir")
        self.submit = QtWidgets.QPushButton(Insert_User)
        self.submit.setGeometry(QtCore.QRect(240, 240, 100, 41))
        self.kembali = QtWidgets.QPushButton(Insert_User)
        self.kembali.setGeometry(QtCore.QRect(80, 240, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.kembali.setFont(font)
        self.kembali.setObjectName("submit")

        self.retranslateUi(Insert_User)
        QtCore.QMetaObject.connectSlotsByName(Insert_User)
        
        self.submit.clicked.connect(self.Insert_data)
        self.kembali.clicked.connect(self.btnkembali)

    def retranslateUi(self, Insert_User):
        _translate = QtCore.QCoreApplication.translate
        Insert_User.setWindowTitle(_translate("Insert_User", "Insert_User"))
        self.label_judul.setText(_translate("Insert_User", "Input data user"))
        self.label_nama.setText(_translate("Insert_User", "nama"))
        self.label_username.setText(_translate("Insert_User", "username"))
        self.label_pw.setText(_translate("Insert_User", "password"))
        self.label_lv.setText(_translate("Insert_User", "level"))
        self.submit.setText(_translate("Insert_User", "Submit"))
        self.kembali.setText(_translate("Insert_User", "Kembali"))
        
    def Insert_data(self):
        nama_baru = self.L_nama.text()
        username_baru = self.L_username.text()
        password_baru = self.L_pw.text()
        level_baru = self.comboBox_level.currentText()
        User.insert_data(nama_baru, username_baru, password_baru, level_baru)

        self.L_nama.clear()
        self.L_username.clear()
        self.L_pw.clear()
        self.comboBox_level.clear()
        
    def btnkembali(self):
        self.Form.close()
        
        from dashboard_admin import Ui_DashboardAdmin
        self.dashboard_kasir = QDialog()
        self.ui_dashboard_kasir = Ui_DashboardAdmin()
        self.ui_dashboard_kasir.setupUi(self.dashboard_kasir)
        self.dashboard_kasir.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_insert()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
