# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_pegawai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from departemen import departemen
from pegawai import pegawai
from PyQt5.QtWidgets import QDialog
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt


class Ui_Insert_Pegawai(object):
    def setupUi(self, Insert_Pegawai):
        self.back = Insert_Pegawai
        Insert_Pegawai.setObjectName("Insert_Pegawai")
        Insert_Pegawai.resize(389, 600)
        self.label_judul = QtWidgets.QLabel(Insert_Pegawai)
        self.label_judul.setGeometry(QtCore.QRect(10, 10, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judul.setObjectName("label_judul")
        self.label_nip = QtWidgets.QLabel(Insert_Pegawai)
        self.label_nip.setGeometry(QtCore.QRect(30, 80, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nip.setFont(font)
        self.label_nip.setObjectName("label_nip")
        self.label_nama = QtWidgets.QLabel(Insert_Pegawai)
        self.label_nama.setGeometry(QtCore.QRect(30, 120, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.label_hp = QtWidgets.QLabel(Insert_Pegawai)
        self.label_hp.setGeometry(QtCore.QRect(30, 160, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hp.setFont(font)
        self.label_hp.setObjectName("label_hp")
        self.label_jabaatan = QtWidgets.QLabel(Insert_Pegawai)
        self.label_jabaatan.setGeometry(QtCore.QRect(30, 200, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_jabaatan.setFont(font)
        self.label_jabaatan.setObjectName("label_jabaatan")
        self.label_alamat = QtWidgets.QLabel(Insert_Pegawai)
        self.label_alamat.setGeometry(QtCore.QRect(30, 240, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_alamat.setFont(font)
        self.label_alamat.setObjectName("label_alamat")
        self.label_departemen = QtWidgets.QLabel(Insert_Pegawai)
        self.label_departemen.setGeometry(QtCore.QRect(30, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_departemen.setFont(font)
        self.label_departemen.setObjectName("label_departemen")
        self.lineEdit_nip = QtWidgets.QLineEdit(Insert_Pegawai)
        self.lineEdit_nip.setGeometry(QtCore.QRect(130, 80, 201, 21))
        self.lineEdit_nip.setObjectName("lineEdit_nip")
        self.lineEdit_nama = QtWidgets.QLineEdit(Insert_Pegawai)
        self.lineEdit_nama.setGeometry(QtCore.QRect(130, 120, 201, 21))
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.lineEdit_hp = QtWidgets.QLineEdit(Insert_Pegawai)
        self.lineEdit_hp.setGeometry(QtCore.QRect(130, 160, 201, 21))
        self.lineEdit_hp.setObjectName("lineEdit_hp")
        self.lineEdit_alamat = QtWidgets.QLineEdit(Insert_Pegawai)
        self.lineEdit_alamat.setGeometry(QtCore.QRect(130, 240, 201, 41))
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.lineEdit_jabatan = QtWidgets.QLineEdit(Insert_Pegawai)
        self.lineEdit_jabatan.setGeometry(QtCore.QRect(130, 200, 201, 21))
        self.lineEdit_jabatan.setObjectName("lineEdit_jabatan")
        self.comboBox_departemen = QtWidgets.QComboBox(Insert_Pegawai)
        self.comboBox_departemen.setGeometry(QtCore.QRect(130, 300, 201, 22))
        self.comboBox_departemen.setObjectName("comboBox_departemen")
        self.simpan = QtWidgets.QPushButton(Insert_Pegawai)
        self.simpan.setGeometry(QtCore.QRect(140, 360, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.simpan.setFont(font)
        self.simpan.setAutoFillBackground(False)
        self.simpan.setObjectName("simpan")
        self.pushButton = QtWidgets.QPushButton(Insert_Pegawai)
        self.pushButton.setGeometry(QtCore.QRect(30, 36, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        
        self.browse_button = QtWidgets.QPushButton(Insert_Pegawai)
        self.browse_button.setGeometry(QtCore.QRect(260, 360, 91, 31))
        self.browse_button.setObjectName("browse_button")
        self.browse_button.setText("Browse")
        self.browse_button.clicked.connect(self.browse_image)
        
        self.label_gambar = QtWidgets.QLabel(Insert_Pegawai)
        self.label_gambar.setGeometry(QtCore.QRect(100, 400, 200, 200))
        self.label_gambar.setObjectName("label_gambar")

        self.retranslateUi(Insert_Pegawai)
        QtCore.QMetaObject.connectSlotsByName(Insert_Pegawai)
        
        self.getDataDepartemen()
        self.simpan.clicked.connect(self.insert_pegawai)
        self.pushButton.clicked.connect(self.kembali)

    def retranslateUi(self, Insert_Pegawai):
        _translate = QtCore.QCoreApplication.translate
        Insert_Pegawai.setWindowTitle(_translate("Insert_Pegawai", "Insert Pegawai"))
        self.label_judul.setText(_translate("Insert_Pegawai", "Insert Pegawai "))
        self.label_nip.setText(_translate("Insert_Pegawai", "Nip"))
        self.label_nama.setText(_translate("Insert_Pegawai", "Nama"))
        self.label_hp.setText(_translate("Insert_Pegawai", "Hp"))
        self.label_jabaatan.setText(_translate("Insert_Pegawai", "Jabatan"))
        self.label_alamat.setText(_translate("Insert_Pegawai", "Alamat"))
        self.label_departemen.setText(_translate("Insert_Pegawai", "Departemen"))
        self.simpan.setText(_translate("Insert_Pegawai", "SIMPAN"))
        self.pushButton.setText(_translate("Insert_Pegawai", ""))
        
    def getDataDepartemen(self):
        data = departemen.select_data()
        print(data)
        self.comboBox_departemen.addItems(data)
        

    def browse_image(self):
        options = QFileDialog.Options()
        options = QFileDialog.ReadOnly
        file_path, _ = QFileDialog.getOpenFileName(self.back, "Pilih Gambar Pegawai", "", "Images (*.png *.xpm *.jpg *.bmp);;All Files (*)", options=options)

        if file_path:
            pixmap = QPixmap(file_path)

            # Menyusuaikan ukuran gambar menjadi 100x100
            pixmap = pixmap.scaled(200, 200, Qt.KeepAspectRatio)

            self.label_gambar.setPixmap(pixmap)

            with open(file_path, "rb") as file:
                image_data = file.read()

            # Simpan image_data ke dalam variabel untuk kemudian digunakan dalam insert_data
            self.image_data = image_data
        
    def insert_pegawai(self):
        nip = self.lineEdit_nip.text()
        nama = self.lineEdit_nama.text()
        hp = self.lineEdit_hp.text()
        jabatan = self.lineEdit_jabatan.text()
        alamat = self.lineEdit_alamat.text()
        ins_departemen = self.comboBox_departemen.currentText()

        # Gunakan self.image_data yang telah diisi saat gambar dipilih
        if hasattr(self, 'image_data'):
            pegawai.insert_data(nip, nama, hp, jabatan, alamat, ins_departemen, self.image_data)
        else:
            pegawai.insert_data(nip, nama, hp, jabatan, alamat, ins_departemen)

        self.lineEdit_nip.clear()
        self.lineEdit_nama.clear()
        self.lineEdit_hp.clear()
        self.lineEdit_jabatan.clear()
        self.lineEdit_alamat.clear()
        self.comboBox_departemen.clear()
        self.label_gambar.clear()
        
    def kembali(self):
        self.back.close()
        
        from dashboard_pegawai import Ui_Dashboardpegawai
        self.dashboard_pegawai = QDialog()
        self.ui_dashboard_pegawai = Ui_Dashboardpegawai()
        self.ui_dashboard_pegawai.setupUi(self.dashboard_pegawai)
        self.dashboard_pegawai.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Insert_Pegawai = QtWidgets.QWidget()
    ui = Ui_Insert_Pegawai()
    ui.setupUi(Insert_Pegawai)
    Insert_Pegawai.show()
    sys.exit(app.exec_())
