# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tambah_data_brg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Barang import Barang
from kategori import kategori
from PyQt5.QtWidgets import QDialog



class Ui_Insert(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Insert Barang")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 90, 35, 10))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 35, 10))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 35, 10))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 35, 10))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 35, 10))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 250, 61, 20))
        self.pushButton.setObjectName("pushButton")
        self.btn_kembali = QtWidgets.QPushButton(Dialog)
        self.btn_kembali.setGeometry(QtCore.QRect(150, 250, 61, 20))
        self.btn_kembali.setObjectName("btn_kembali")
        self.btn_kembali.setText("Kembali")
        self.box_id = QtWidgets.QLineEdit(Dialog)
        self.box_id.setGeometry(QtCore.QRect(120, 80, 151, 20))
        self.box_id.setObjectName("box_id")
        self.box_nam = QtWidgets.QLineEdit(Dialog)
        self.box_nam.setGeometry(QtCore.QRect(120, 110, 151, 20))
        self.box_nam.setObjectName("box_nam")
        self.box_stok = QtWidgets.QLineEdit(Dialog)
        self.box_stok.setGeometry(QtCore.QRect(120, 140, 151, 20))
        self.box_stok.setObjectName("box_stok")
        self.box_harga = QtWidgets.QLineEdit(Dialog)
        self.box_harga.setGeometry(QtCore.QRect(120, 170, 151, 20))
        self.box_harga.setObjectName("box_harga")
        self.comboBox_kategori = QtWidgets.QComboBox(Dialog)
        self.comboBox_kategori.setGeometry(QtCore.QRect(120, 210, 151, 22))
        self.comboBox_kategori.setObjectName("comboBox_kategori")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(110, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.getDataCategori()
        self.pushButton.clicked.connect(self.Insertbrg)
        self.btn_kembali.clicked.connect(self.kembali)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def getDataCategori(self):
        data = kategori.select_data()
        print(data)
        self.comboBox_kategori.addItems(data)
    
    def Insertbrg(self):
        id = self.box_id.text()
        nama = self.box_nam.text()
        stok = self.box_stok.text()
        harga = self.box_harga.text()
        kategori = self.comboBox_kategori.currentText()
        Barang.insert_data(id,nama,stok,harga,kategori)
        
        self.box_id.clear()
        self.box_nam.clear()
        self.box_stok.clear()
        self.box_harga.clear()
        self.comboBox_kategori.clear()
        
    def kembali(self):
        self.Dialog.close()
        
        from dashboard_kasir import Ui_DashboardKasir
        self.dashboard_kasir = QDialog()
        self.ui_dashboard_kasir = Ui_DashboardKasir()
        self.ui_dashboard_kasir.setupUi(self.dashboard_kasir)
        self.dashboard_kasir.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ID"))
        self.label_2.setText(_translate("Dialog", "Nama"))
        self.label_3.setText(_translate("Dialog", "Stok"))
        self.label_4.setText(_translate("Dialog", "Harga"))
        self.label_5.setText(_translate("Dialog", "Kategori"))
        self.pushButton.setText(_translate("Dialog", "Simpan"))
        self.label_6.setText(_translate("Dialog", "Tambah Data Barang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Insert()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
