# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_brg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from Barang import Barang



class Ui_Databrg(object):
    def setupUi(self, Form):
        self.Form = Form
        Form.setObjectName("Form")
        Form.resize(583, 357)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 531, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 10, 171, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(470, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton.clicked.connect(self.kembali)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Data Barang", "Data Barang"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Data Barang", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Data Barang", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Data Barang", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Data Barang", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Data Barang", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Data Barang", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Data Barang", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Data Barang", "Stok"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Data Barang", "Harga"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Data Barang", "Kategori"))
        self.label.setText(_translate("Data Barang", "Data Barang"))
        self.pushButton.setText(_translate("Data Barang", "Kembali"))
        
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        
        data = self.lihat()  # Dapatkan data terlebih dahulu
        row_count = len(data)

        self.tableWidget.setRowCount(row_count)
        
        for baris in range(row_count):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(baris, item)

            for kolom, value in enumerate(data[baris]):
                item = QtWidgets.QTableWidgetItem(str(value))
                self.tableWidget.setItem(baris, kolom, item)
                
        self.tableWidget.setSortingEnabled(__sortingEnabled)

    def lihat(self):
        usr = Barang()
        a = usr.nilai()
        print(a)
        return a
    
    def kembali(self):
        self.Form.close()
        
        from dashboard_kasir import Ui_DashboardKasir
        self.dashboard_kasir = QDialog()
        self.ui_dashboard_kasir = Ui_DashboardKasir()
        self.ui_dashboard_kasir.setupUi(self.dashboard_kasir)
        self.dashboard_kasir.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Databrg()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
    