# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from User import User
from PyQt5.QtWidgets import QDialog

class Ui_DataUser(object):
    def setupUi(self, DataUser):
        self.Form = DataUser
        DataUser.setObjectName("DataUser")
        DataUser.resize(474, 256)
        self.tableWidget = QtWidgets.QTableWidget(DataUser)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 431, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.label = QtWidgets.QLabel(DataUser)
        self.label.setGeometry(QtCore.QRect(30, 10, 131, 31))
        self.pushButton = QtWidgets.QPushButton(DataUser)
        self.pushButton.setGeometry(QtCore.QRect(370, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.pushButton.clicked.connect(self.btnkembali)

        self.retranslateUi(DataUser)
        QtCore.QMetaObject.connectSlotsByName(DataUser)
        

    def retranslateUi(self, DataUser):
        _translate = QtCore.QCoreApplication.translate
        DataUser.setWindowTitle(_translate("DataUser", "Data User"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("DataUser", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("DataUser", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("DataUser", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("DataUser", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("DataUser", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DataUser", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DataUser", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DataUser", "Password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DataUser", "Level"))
        self.pushButton.setText(_translate("Data Barang", "Kembali"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        

        self.label.setText(_translate("DataUser", "Data User"))

        # PERULANAGAN DISINI
        data = self.lihat()  # Dapatkan data terlebih dahulu
        row_count = len(data)

        self.tableWidget.setRowCount(row_count)
        
        for baris in range(row_count):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(baris, item)

            for kolom, value in enumerate(data[baris]):
                item = QtWidgets.QTableWidgetItem(str(value))
                self.tableWidget.setItem(baris, kolom, item)

        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("DataUser", "Data User"))
        
    def lihat(self):
        usr = User()
        a = usr.nilai()
        return a
    
    def row(self):
        user = User()
        nilai = int(str(user.nilai()).replace(",","").replace(")","").replace("(",""))
        return nilai
    
    def btnkembali(self):
        self.Form.close()
        
        from dashboard_admin import Ui_DashboardAdmin
        self.dashboard_kasir = QDialog()
        self.ui_dashboard_kasir = Ui_DashboardAdmin()
        self.ui_dashboard_kasir.setupUi(self.dashboard_kasir)
        self.dashboard_kasir.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataUser = QtWidgets.QWidget()
    ui = Ui_DataUser()
    ui.setupUi(DataUser)
    DataUser.show()
    sys.exit(app.exec_())
