# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dashboard_admin  as da
import dashboard_kasir as dk
from User import User


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.dialog = Dialog 
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(150, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 110, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 101, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Username = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Username.setGeometry(QtCore.QRect(120, 110, 201, 20))
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Password.setGeometry(QtCore.QRect(120, 150, 201, 20))
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.pushButton_Login = QtWidgets.QPushButton(Dialog)
        self.pushButton_Login.setGeometry(QtCore.QRect(120, 210, 141, 17))
        self.pushButton_Login.setObjectName("pushButton_Login")
        
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.pushButton_Login.clicked.connect(self.login)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "FORM LOGIN"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.pushButton_Login.setText(_translate("Dialog", "Login"))
        
    def openDA(self):
        self.dialog.close()
        
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_DashboardAdmin()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openDK(self):
        self.dialog.close()
        
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_DashboardKasir()
        self.ui.setupUi(self.window)
        self.window.show()

    def login(self):
        username = self.lineEdit_Username.text()
        password = self.lineEdit_Password.text()
        lvl_login = User.login(username,password)
        if (lvl_login == "Admin"):
            self.openDA()
        elif(lvl_login == "kasir"):
            self.openDK()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
