# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_pegawai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pegawai import pegawai
from PyQt5.QtWidgets import QDialog
from departemen import departemen
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt
from PyQt5.QtCore import QByteArray

class Ui_Update_Pegawai(object):
    def setupUi(self, Update_Pegawai):
        self.Form = Update_Pegawai
        self.back = Update_Pegawai
        Update_Pegawai.setObjectName("Update_Pegawai")
        Update_Pegawai.resize(413, 600)
        self.label_judul = QtWidgets.QLabel(Update_Pegawai)
        self.label_judul.setGeometry(QtCore.QRect(10, 10, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judul.setObjectName("label_judul")
        self.label_nip = QtWidgets.QLabel(Update_Pegawai)
        self.label_nip.setGeometry(QtCore.QRect(30, 80, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nip.setFont(font)
        self.label_nip.setObjectName("label_nip")
        self.label_nama = QtWidgets.QLabel(Update_Pegawai)
        self.label_nama.setGeometry(QtCore.QRect(30, 120, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.label_hp = QtWidgets.QLabel(Update_Pegawai)
        self.label_hp.setGeometry(QtCore.QRect(30, 160, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_hp.setFont(font)
        self.label_hp.setObjectName("label_hp")
        self.label_jabaatan = QtWidgets.QLabel(Update_Pegawai)
        self.label_jabaatan.setGeometry(QtCore.QRect(30, 200, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_jabaatan.setFont(font)
        self.label_jabaatan.setObjectName("label_jabaatan")
        self.label_alamat = QtWidgets.QLabel(Update_Pegawai)
        self.label_alamat.setGeometry(QtCore.QRect(30, 240, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_alamat.setFont(font)
        self.label_alamat.setObjectName("label_alamat")
        self.label_departemen = QtWidgets.QLabel(Update_Pegawai)
        self.label_departemen.setGeometry(QtCore.QRect(30, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_departemen.setFont(font)
        self.label_departemen.setObjectName("label_departemen")
        self.lineEdit_nip = QtWidgets.QLineEdit(Update_Pegawai)
        self.lineEdit_nip.setGeometry(QtCore.QRect(130, 80, 201, 21))
        self.lineEdit_nip.setObjectName("lineEdit_nip")
        self.lineEdit_nama = QtWidgets.QLineEdit(Update_Pegawai)
        self.lineEdit_nama.setGeometry(QtCore.QRect(130, 120, 201, 21))
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.lineEdit_hp = QtWidgets.QLineEdit(Update_Pegawai)
        self.lineEdit_hp.setGeometry(QtCore.QRect(130, 160, 201, 21))
        self.lineEdit_hp.setObjectName("lineEdit_hp")
        self.lineEdit_alamat = QtWidgets.QLineEdit(Update_Pegawai)
        self.lineEdit_alamat.setGeometry(QtCore.QRect(130, 240, 201, 41))
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.lineEdit_jabatan = QtWidgets.QLineEdit(Update_Pegawai)
        self.lineEdit_jabatan.setGeometry(QtCore.QRect(130, 200, 201, 21))
        self.lineEdit_jabatan.setObjectName("lineEdit_jabatan")
        self.comboBox_departemen = QtWidgets.QComboBox(Update_Pegawai)
        self.comboBox_departemen.setGeometry(QtCore.QRect(130, 300, 201, 22))
        self.comboBox_departemen.setObjectName("comboBox_departemen")
        self.update = QtWidgets.QPushButton(Update_Pegawai)
        self.update.setGeometry(QtCore.QRect(140, 360, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setAutoFillBackground(False)
        self.update.setObjectName("update")
        self.kembali = QtWidgets.QPushButton(Update_Pegawai)
        self.kembali.setGeometry(QtCore.QRect(30, 360, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kembali.setFont(font)
        self.kembali.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.kembali.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Kuliah/Semester 3/PBO/icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kembali.setIcon(icon)
        self.kembali.setIconSize(QtCore.QSize(20, 20))
        self.kembali.setObjectName("kembali")
        self.pushButton_2 = QtWidgets.QPushButton(Update_Pegawai)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 80, 51, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.browse_button = QtWidgets.QPushButton(Update_Pegawai)
        self.browse_button.setGeometry(QtCore.QRect(260, 360, 91, 31))
        self.browse_button.setObjectName("browse_button")
        self.browse_button.setText("Browse")
        self.browse_button.clicked.connect(self.browse_image)
        
        self.label_gambar = QtWidgets.QLabel(Update_Pegawai)
        self.label_gambar.setGeometry(QtCore.QRect(100, 400, 200, 200))
        self.label_gambar.setObjectName("label_gambar")

        self.retranslateUi(Update_Pegawai)
        QtCore.QMetaObject.connectSlotsByName(Update_Pegawai)
        
        self.getDatadepartemen()
        
        self.pushButton_2.clicked.connect(self.cariData)
        self.kembali.clicked.connect(self.btnkembali)
        self.update.clicked.connect(self.ubah)

    def retranslateUi(self, Update_Pegawai):
        _translate = QtCore.QCoreApplication.translate
        Update_Pegawai.setWindowTitle(_translate("Update_Pegawai", "Insert Pegawai"))
        self.label_judul.setText(_translate("Update_Pegawai", "Update Pegawai "))
        self.label_nip.setText(_translate("Update_Pegawai", "Nip"))
        self.label_nama.setText(_translate("Update_Pegawai", "Nama"))
        self.label_hp.setText(_translate("Update_Pegawai", "Hp"))
        self.label_jabaatan.setText(_translate("Update_Pegawai", "Jabatan"))
        self.label_alamat.setText(_translate("Update_Pegawai", "Alamat"))
        self.label_departemen.setText(_translate("Update_Pegawai", "Departemen"))
        self.update.setText(_translate("Update_Pegawai", "UPDATE"))
        self.kembali.setText(_translate("Update_Pegawai", ""))
        self.pushButton_2.setText(_translate("Update_Pegawai", "Cari"))
        
    def getDatadepartemen(self):
        data = departemen.select_data()
        print(data)
        self.comboBox_departemen.addItems(data)
        
    # def browse_image(self):
    #     options = QFileDialog.Options()
    #     options |= QFileDialog.ReadOnly
    #     file_path, _ = QFileDialog.getOpenFileName(self.back, "Pilih Gambar Pegawai", "", "Images (*.png *.xpm *.jpg *.bmp);;All Files (*)", options=options)

    #     if file_path:
    #         pixmap = QPixmap(file_path)

    #         # Menyusuaikan ukuran gambar menjadi 100x100
    #         pixmap = pixmap.scaled(200, 200, Qt.KeepAspectRatio)

    #         self.label_gambar.setPixmap(pixmap)

    #         with open(file_path, "rb") as file:
    #             image_data = file.read()

    #         # Simpan image_data ke dalam variabel untuk kemudian digunakan dalam insert_data
    #         self.image_data = image_data



    def cariData(self):
        nip = self.lineEdit_nip.text()
        data = pegawai.cari_data(nip)

        print("Raw data:", data)  # Print raw data for debugging

        # Check if data is not empty and has enough elements
        if data and len(data) >= 6:  # Adjust the condition to match the actual length
            namaq = data[1]
            hpq = data[2]
            jabatanq = data[3]
            alamatq = data[4]
            departemenq = data[5]
            image_data = data[6]

            print(data)

            # Check if BLOB data is available
            if len(data) >= 7:
                # image_data = data[6]

                # Convert BLOB data to a QByteArray
                byte_array = QByteArray(image_data)

                # Display the image
                pixmap = QPixmap()
                pixmap.loadFromData(byte_array)
                pixmap = pixmap.scaled(200, 200, Qt.KeepAspectRatio)
                self.label_gambar.setPixmap(pixmap)

                pegawai.update_data(namaq, hpq, jabatanq, alamatq, departemenq, image_data, nip)

            self.lineEdit_nama.setText(str(namaq))
            self.lineEdit_hp.setText(str(hpq))
            self.lineEdit_jabatan.setText(str(jabatanq))
            self.lineEdit_alamat.setText(str(alamatq))
            self.label_gambar.setText(image_data)
            self.comboBox_departemen.setCurrentText(str(departemenq))
        else:
            print("Data not found or incomplete.")

        
    def ubah(self):
        nama = self.lineEdit_nama.text()
        nip_to_update = self.lineEdit_nip.text()
        jabatan = self.lineEdit_jabatan.text()
        departemen = self.comboBox_departemen.currentText()
        alamat =  self.lineEdit_alamat.text()
        hp = self.lineEdit_hp.text()
        
        if hasattr(self, 'image_data'):
            pegawai.update_data(nama, hp, jabatan, alamat, departemen, self.image_data, nip_to_update)
        
        self.lineEdit_nip.clear()
        self.lineEdit_nama.clear()
        self.lineEdit_hp.clear()
        self.lineEdit_jabatan.clear()
        self.lineEdit_alamat.clear()
        self.comboBox_departemen.clear()
        self.label_gambar.clear()
        
    def btnkembali(self):
        self.Form.close()
        
        from dashboard_pegawai import Ui_Dashboardpegawai
        self.dashboard_pegawai = QDialog()
        self.ui_dashboard_pegawai = Ui_Dashboardpegawai()
        self.ui_dashboard_pegawai.setupUi(self.dashboard_pegawai)
        self.dashboard_pegawai.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Update_Pegawai = QtWidgets.QWidget()
    ui = Ui_Update_Pegawai()
    ui.setupUi(Update_Pegawai)
    Update_Pegawai.show()
    sys.exit(app.exec_())
