# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from User import User
from PyQt5.QtWidgets import QDialog

class Ui_update(object):
    def setupUi(self, update_du):
        self.Form = update_du
        update_du.setObjectName("update_du")
        update_du.resize(400, 300)
        self.label_judul = QtWidgets.QLabel(update_du)
        self.label_judul.setGeometry(QtCore.QRect(120, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setObjectName("label_judul")
        self.label_lv = QtWidgets.QLabel(update_du)
        self.label_lv.setGeometry(QtCore.QRect(40, 200, 47, 13))
        self.label_lv.setObjectName("label_lv")
        self.L_nama = QtWidgets.QLineEdit(update_du)
        self.L_nama.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.L_nama.setObjectName("L_nama")
        self.L_username = QtWidgets.QLineEdit(update_du)
        self.L_username.setGeometry(QtCore.QRect(150, 100, 201, 20))
        self.L_username.setObjectName("L_username")
        self.update = QtWidgets.QPushButton(update_du)
        self.update.setGeometry(QtCore.QRect(240, 240, 100, 41))
        self.kembali = QtWidgets.QPushButton(update_du)
        self.kembali.setGeometry(QtCore.QRect(70, 240, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setObjectName("update")
        self.kembali.setFont(font)
        self.kembali.setObjectName("kembali")
        self.comboBox_level = QtWidgets.QComboBox(update_du)
        self.comboBox_level.setGeometry(QtCore.QRect(150, 200, 201, 20))
        self.comboBox_level.setObjectName("comboBox_level")
        self.comboBox_level.addItem("Admin")
        self.comboBox_level.addItem("kasir")
        self.label_username_2 = QtWidgets.QLabel(update_du)
        self.label_username_2.setGeometry(QtCore.QRect(40, 60, 47, 13))
        self.label_username_2.setObjectName("label_username_2")
        self.L_pw = QtWidgets.QLineEdit(update_du)
        self.L_pw.setGeometry(QtCore.QRect(150, 150, 201, 20))
        self.L_pw.setObjectName("L_pw")
        self.label_pw = QtWidgets.QLabel(update_du)
        self.label_pw.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.label_pw.setObjectName("label_pw")
        self.label_nama = QtWidgets.QLabel(update_du)
        self.label_nama.setGeometry(QtCore.QRect(40, 100, 47, 13))
        self.label_nama.setObjectName("label_nama")
        self.pushButton = QtWidgets.QPushButton(update_du)
        self.pushButton.setGeometry(QtCore.QRect(280, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(update_du)
        QtCore.QMetaObject.connectSlotsByName(update_du)
        
        self.pushButton.clicked.connect(self.cari)
        self.update.clicked.connect(self.ubah)
        self.kembali.clicked.connect(self.btnkembali)

    def retranslateUi(self, update_du):
        _translate = QtCore.QCoreApplication.translate
        update_du.setWindowTitle(_translate("update_du", "Update User"))
        self.label_judul.setText(_translate("update_du", "Update data user"))
        self.label_lv.setText(_translate("update_du", "level"))
        self.update.setText(_translate("update_du", "Update"))
        self.kembali.setText(_translate("update_du", "Kembali"))
        self.label_username_2.setText(_translate("update_du", "username"))
        self.label_pw.setText(_translate("update_du", "password"))
        self.label_nama.setText(_translate("update_du", "nama"))
        self.pushButton.setText(_translate("update_du", "cari"))
        
    def cari(self):
        self.usr = User
        
        username = self.L_nama.text()
        
        myresult = self.usr.cari_data(username)
        
        print(myresult)
        self.L_username.setText(myresult[0])
        self.L_pw.setText(myresult[2])
        level_index = self.comboBox_level.findText(myresult[-1])
        self.comboBox_level.setCurrentIndex(level_index)
        
    def ubah(self):
        nama = self.L_username.text()
        pw = self.L_pw.text()
        lv = self.comboBox_level.currentText()
        self.usr.update_data(nama, pw, lv, self.L_nama.text())
        
        self.L_nama.clear()
        self.L_username.clear()
        self.L_pw.clear()
        self.comboBox_level.clear()
        
    def btnkembali(self):
        self.Form.close()
        
        from dashboard_admin import Ui_DashboardAdmin
        self.dashboard_kasir = QDialog()
        self.ui_dashboard_kasir = Ui_DashboardAdmin()
        self.ui_dashboard_kasir.setupUi(self.dashboard_kasir)
        self.dashboard_kasir.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_du = QtWidgets.QWidget()
    ui = Ui_update()
    ui.setupUi(update_du)
    update_du.show()
    sys.exit(app.exec_())
