# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard_mhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import form_login as l
import lihat_ints_mhs as li
import tambah_kelompok_mhs as tkm
import lihat_kelompok_mhs as lkm

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dialog = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(352, 404, 103, 34))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_instansi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_instansi.setGeometry(QtCore.QRect(90, 294, 123, 34))
        self.pushButton_instansi.setObjectName("pushButton_instansi")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(335, 294, 133, 39))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(585, 294, 133, 39))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(5, 4, 787, 536))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\pbo kelompok 5\\resourse png\\mahasiswa.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_logout.raise_()
        self.pushButton_instansi.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_instansi.clicked.connect(self.lihatINS)
        self.pushButton_2.clicked.connect(self.tambahKLMPK)
        self.pushButton_3.clicked.connect(self.lihatKLP)
        self.pushButton_logout.clicked.connect(self.logout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
        self.pushButton_instansi.setText(_translate("MainWindow", "MASUK"))
        self.pushButton_2.setText(_translate("MainWindow", "MASUK"))
        self.pushButton_3.setText(_translate("MainWindow", "MASUK"))

    def lihatINS(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = li.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def lihatKLP(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = lkm.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def tambahKLMPK(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = tkm.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = l.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
