# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard_user_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dashboard_admin as da
import ubah_user as uu
import delete_user as du
import lihat_user as lu

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dialog = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_view = QtWidgets.QPushButton(self.centralwidget)
        self.btn_view.setGeometry(QtCore.QRect(519, 413, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_view.setFont(font)
        self.btn_view.setObjectName("btn_view")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(151, 415, 120, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(336, 202, 120, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_insert.setFont(font)
        self.btn_insert.setObjectName("btn_insert")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(330, 384, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setObjectName("btn_logout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, 4, 787, 534))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\pbo kelompok 5\\resourse png\\dashboard User.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.btn_view.raise_()
        self.btn_delete.raise_()
        self.btn_insert.raise_()
        self.btn_logout.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_logout.clicked.connect(self.kembali)
        self.btn_insert.clicked.connect(self.openUU)
        self.btn_delete.clicked.connect(self.openDU)
        self.btn_view.clicked.connect(self.openLU)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_view.setText(_translate("MainWindow", "Masuk"))
        self.btn_delete.setText(_translate("MainWindow", "Masuk"))
        self.btn_insert.setText(_translate("MainWindow", "Masuk"))
        self.btn_logout.setText(_translate("MainWindow", "Kembali"))

    def openUU(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = uu.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDU(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = du.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openLU(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = lu.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def kembali(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
