# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard_instansi_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dashboard_admin as da
import form_admin_delete_data_instansi as faddi
import form_admin_tambah_data_instansi as fatdi
import form_admin_ubah_data_instansi as faudi
import lihat_ints as li

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dialog = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(336, 291, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setObjectName("btn_logout")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(147, 204, 127, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_insert.setFont(font)
        self.btn_insert.setObjectName("btn_insert")
        self.btn_update = QtWidgets.QPushButton(self.centralwidget)
        self.btn_update.setGeometry(QtCore.QRect(525, 204, 127, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update.setFont(font)
        self.btn_update.setObjectName("btn_update")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(149, 424, 127, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")
        self.btn_view = QtWidgets.QPushButton(self.centralwidget)
        self.btn_view.setGeometry(QtCore.QRect(521, 425, 127, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_view.setFont(font)
        self.btn_view.setObjectName("btn_view")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -2, 791, 557))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\pbo kelompok 5\\resourse png\\dashboard Instansi.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.btn_logout.raise_()
        self.btn_insert.raise_()
        self.btn_update.raise_()
        self.btn_delete.raise_()
        self.btn_view.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_insert.clicked.connect(self.openFATDI)
        self.btn_update.clicked.connect(self.openFAUDI)
        self.btn_delete.clicked.connect(self.openFADDI)
        self.btn_logout.clicked.connect(self.kembali)
        self.btn_view.clicked.connect(self.openLI)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_logout.setText(_translate("MainWindow", "LOGOUT"))
        self.btn_insert.setText(_translate("MainWindow", "MASUK"))
        self.btn_update.setText(_translate("MainWindow", "MASUK"))
        self.btn_delete.setText(_translate("MainWindow", "MASUK"))
        self.btn_view.setText(_translate("MainWindow", "MASUK"))

    def openFADDI(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = faddi.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openFATDI(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = fatdi.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openFAUDI(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = faudi.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openLI(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = li.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def kembali(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
