# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import form_login as l
import dashboard_dosen_admin as dda
import dashboard_instansi_admin as dia
import dashboard_kelompok_admin as dka
import dashboard_mahasiswa_admin as dma
import dashboard_user_admin as dua

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dialog = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_mhs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mhs.setGeometry(QtCore.QRect(367, 414, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_mhs.setFont(font)
        self.btn_mhs.setObjectName("btn_mhs")
        self.btn_dosen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dosen.setGeometry(QtCore.QRect(151, 415, 120, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_dosen.setFont(font)
        self.btn_dosen.setObjectName("btn_dosen")
        self.btn_instansi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_instansi.setGeometry(QtCore.QRect(371, 201, 120, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_instansi.setFont(font)
        self.btn_instansi.setObjectName("btn_instansi")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(589, 431, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1, -1, 796, 541))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\pbo kelompok 5\\resourse png\\dashboard_admin.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btn_user = QtWidgets.QPushButton(self.centralwidget)
        self.btn_user.setGeometry(QtCore.QRect(151, 201, 120, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_user.setFont(font)
        self.btn_user.setAutoFillBackground(False)
        self.btn_user.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.btn_user.setAutoDefault(False)
        self.btn_user.setDefault(False)
        self.btn_user.setFlat(False)
        self.btn_user.setObjectName("btn_user")
        self.btn_mhs_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mhs_2.setGeometry(QtCore.QRect(596, 298, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_mhs_2.setFont(font)
        self.btn_mhs_2.setObjectName("btn_mhs_2")
        self.label_2.raise_()
        self.btn_mhs.raise_()
        self.btn_dosen.raise_()
        self.btn_instansi.raise_()
        self.btn.raise_()
        self.btn_user.raise_()
        self.btn_mhs_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn.clicked.connect(self.logout)
        self.btn_user.clicked.connect(self.openUA)
        self.btn_instansi.clicked.connect(self.openIA)
        self.btn_dosen.clicked.connect(self.openDA)
        self.btn_mhs.clicked.connect(self.openMA)
        self.btn_mhs_2.clicked.connect(self.openKA)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_mhs.setText(_translate("MainWindow", "Masuk"))
        self.btn_dosen.setText(_translate("MainWindow", "Masuk"))
        self.btn_instansi.setText(_translate("MainWindow", "Masuk"))
        self.btn.setText(_translate("MainWindow", "LOGOUT"))
        self.btn_user.setText(_translate("MainWindow", "Masuk"))
        self.btn_mhs_2.setText(_translate("MainWindow", "Masuk"))
        
    def openKA(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = dka.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openUA(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = dua.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openMA(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = dma.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDA(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = dda.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openIA(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = dia.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = l.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
