# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard_dosen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import form_login as l
import lihat_mhs_dsn as lm
import lihat_dsn_dsn as ld
import lihat_ints_dsn as li
import lihat_kelompok_dsn as lkd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dialog = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(3, 3, 791, 536))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\pbo kelompok 5\\resourse png\\dosen.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(340, 420, 122, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setObjectName("btn_logout")
        self.btn_lihat_instansi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lihat_instansi.setGeometry(QtCore.QRect(151, 195, 122, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lihat_instansi.setFont(font)
        self.btn_lihat_instansi.setObjectName("btn_lihat_instansi")
        self.btn_lihat_dosen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lihat_dosen.setGeometry(QtCore.QRect(528, 198, 122, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lihat_dosen.setFont(font)
        self.btn_lihat_dosen.setObjectName("btn_lihat_dosen")
        self.btn_lihat_mhs = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lihat_mhs.setGeometry(QtCore.QRect(151, 420, 122, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lihat_mhs.setFont(font)
        self.btn_lihat_mhs.setObjectName("btn_lihat_mhs")
        self.btn_lihat_klp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lihat_klp.setGeometry(QtCore.QRect(528, 420, 122, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_lihat_klp.setFont(font)
        self.btn_lihat_klp.setObjectName("btn_lihat_klp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_lihat_mhs.clicked.connect(self.lihatMHS)
        self.btn_lihat_dosen.clicked.connect(self.lihatDSN)
        self.btn_lihat_instansi.clicked.connect(self.lihatINS)
        self.btn_logout.clicked.connect(self.logout)
        self.btn_lihat_klp.clicked.connect(self.lihatKLP)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_logout.setText(_translate("MainWindow", "LOGOUT"))
        self.btn_lihat_instansi.setText(_translate("MainWindow", "LIHAT"))
        self.btn_lihat_dosen.setText(_translate("MainWindow", "LIHAT"))
        self.btn_lihat_mhs.setText(_translate("MainWindow", "LIHAT"))
        self.btn_lihat_klp.setText(_translate("MainWindow", "LIHAT"))

    def lihatMHS(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = lm.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def lihatDSN(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = ld.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def lihatINS(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = li.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def lihatKLP(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = lkd.Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

        

    def logout(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = l.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
