# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dashboard_admin as da
import dashboard_mhs as dm
import dashboard_dosen as ds
import form_register as fr
from User import User

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dialog = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(399, 380, 87, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.LineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_username.setGeometry(QtCore.QRect(411, 196, 304, 39))
        self.LineEdit_username.setObjectName("LineEdit_username")
        self.btn_daftar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_daftar.setGeometry(QtCore.QRect(621, 380, 87, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_daftar.setFont(font)
        self.btn_daftar.setObjectName("btn_daftar")
        self.LineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_password.setGeometry(QtCore.QRect(411, 283, 304, 39))
        self.LineEdit_password.setObjectName("LineEdit_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(3, 2, 788, 535))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\pbo kelompok 5\\resourse png\\LOGIN.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.btn_login.raise_()
        self.LineEdit_username.raise_()
        self.btn_daftar.raise_()
        self.LineEdit_password.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btn_login.clicked.connect(self.login)
        self.btn_daftar.clicked.connect(self.daftar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_login.setText(_translate("MainWindow", "LOGIN"))
        self.btn_daftar.setText(_translate("MainWindow", "DAFTAR"))
    
    def openDA(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDM(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = dm.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openDS(self):
        self.dialog.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = ds.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def daftar(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = fr.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def login(self):
        username = self.LineEdit_username.text()
        password = self.LineEdit_password.text()
        lvl_login = User.login(username, password)
        if lvl_login == "admin":
            self.openDA()
        elif lvl_login == "dosen":
            self.openDS()
        elif lvl_login == "mahasiswa":
            self.openDM()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
