# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_kelompok.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from kelompok import Kelompok
import dashboard_dosen as dd

class Ui_Form(object):
    def setupUi(self, Form):
        self.MainWindows = Form
        Form.setObjectName("Form")
        Form.resize(793, 354)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 761, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 60, 731, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(370, 310, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.MainWindow = Form
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.Kembali)
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "DATA KELOMPOK"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID_KELOMPOK"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NAMA"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "KETUA"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Anggota 1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Anggota 2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Dosen"))
        self.pushButton.setText(_translate("Form", "Kembali"))
        kelompok_instance = Kelompok()
        data_kelompok = kelompok_instance.tampil()
        self.tampil(data_kelompok)

    
    def tampil(self, data_kelompok):
        self.tableWidget.setRowCount(0)

        # Set the number of rows based on the length of the data
        self.tableWidget.setRowCount(len(data_kelompok))

        # Iterate through the data and populate the table
        for row, Kelompok in enumerate(data_kelompok):
            for col, value in enumerate(Kelompok):
                self.tableWidget.setItem(row, col, QTableWidgetItem(str(value)))

    def Kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dd.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.MainWindow.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
