# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tambah_kelompok_mhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from kelompok import Kelompok
from mahasiswa import Mahasiswa
from instansi import Instansi
from dosen import Dosen
import dashboard_mhs as dm

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.Main = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(80, 150, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nama.setFont(font)
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(80, 90, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 130, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_tambah = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tambah.setGeometry(QtCore.QRect(290, 470, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_tambah.setFont(font)
        self.btn_tambah.setObjectName("btn_tambah")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(79, 73, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_kembali = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kembali.setGeometry(QtCore.QRect(630, 480, 93, 28))
        self.btn_kembali.setObjectName("btn_kembali")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 240, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_ketua = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ketua.setGeometry(QtCore.QRect(80, 210, 581, 22))
        self.comboBox_ketua.setObjectName("comboBox_ketua")
        self.comboBox_anggota1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_anggota1.setGeometry(QtCore.QRect(80, 260, 581, 22))
        self.comboBox_anggota1.setObjectName("comboBox_anggota1")
        self.comboBox_anggota2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_anggota2.setGeometry(QtCore.QRect(80, 310, 581, 22))
        self.comboBox_anggota2.setObjectName("comboBox_anggota2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 290, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 340, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_instansi = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_instansi.setGeometry(QtCore.QRect(80, 360, 581, 22))
        self.comboBox_instansi.setObjectName("comboBox_instansi")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 390, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(80, 410, 581, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.getDatamhs()
        self.getDatains()
        self.getDatadsn()
        self.btn_tambah.clicked.connect(self.InsertData)
        self.btn_kembali.clicked.connect(self.Kembalia)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "NAMA :"))
        self.btn_tambah.setText(_translate("MainWindow", "TAMBAHKAN!!!"))
        self.label_8.setText(_translate("MainWindow", "ID_KELOMPOK :"))
        self.label_7.setText(_translate("MainWindow", "TAMBAH KELOMPOK"))
        self.label_4.setText(_translate("MainWindow", "KETUA :"))
        self.btn_kembali.setText(_translate("MainWindow", "KEMBALI"))
        self.label_5.setText(_translate("MainWindow", "Anggota 1 :"))
        self.label_6.setText(_translate("MainWindow", "Anggota 2 :"))
        self.label_9.setText(_translate("MainWindow", "Instansi :"))
        self.label_10.setText(_translate("MainWindow", "DOSEN :"))

    def getDatamhs(self,):
        data=Mahasiswa.select_data()
        print(data)
        self.comboBox_ketua.addItems(data)
        self.comboBox_anggota1.addItems(data)
        self.comboBox_anggota2.addItems(data)

    def getDatains(self):
        data=Instansi.select_data()
        print(data)
        self.comboBox_instansi.addItems(data)

    def getDatadsn(self):
        data=Dosen.select_data()
        print(data)
        self.comboBox_5.addItems(data)

    def InsertData(self):
        id=self.lineEdit_id.text()
        nama=self.lineEdit_nama.text()
        ketua=self.comboBox_ketua.currentText()
        anggota_1=self.comboBox_anggota1.currentText()
        anggota_2=self.comboBox_anggota2.currentText()
        instansi=self.comboBox_instansi.currentText()
        dosen=self.comboBox_5.currentText()
        Kelompok.insert_kelompok(id, nama, ketua, anggota_1, anggota_2, instansi, dosen)
        self.lineEdit_id.clear()
        self.lineEdit_nama.clear()
        self.comboBox_ketua.setCurrentIndex(0)
        self.comboBox_anggota1.setCurrentIndex(0)
        self.comboBox_anggota2.setCurrentIndex(0)
        self.comboBox_instansi.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)

    def Kembalia(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dm.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.Main.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
